### PR TITLE
support enums

### PR DESCRIPTION
**Pull request by anyx**

### CODE REVIEW

**Comment by A-ZC-Lau** [comment]
Could you switch from single quotation to double quotations? I should be able to merge after that.

I was thinking I should get Enums too, but since I haven't really used them I haven't bothered with an update :D. Great that you did though.

**Comment by anyx** [comment]
Switched to double quotations. Also I can add a my own simple mutations generator. I'm not sure how many cases it may cover, but it's better than nothing I think.

Anyway, it should be in different PR (if you interested). But it will require a little refactoring this library

**Comment by A-ZC-Lau** [comment]
Yeah, put it into another PR. 

I don't really mind any updates since I don't actively make changes (I can't see any other updates needed ATM since you've made the Enum update).

I can add you as a member if you want.

**Review by A-ZC-Lau — APPROVED** [review]

**Comment by anyx** [comment]
I don't mind

**Comment by anyx** [comment]
@FunnyB0y thank you!

**Pull request merged**
