### PR TITLE
mutations

### PR DESCRIPTION
**Pull request by anyx**

### CODE REVIEW

**Review by A-ZC-Lau — CHANGES_REQUESTED** [review]
I think Mutation needs a `setAlias` function. 

Would also be good to have Mutation tests that include both Enum and setAlias.

These are also breaking changes, but I think overall good changes, so I will update the version to 3.0.0

**Comment by A-ZC-Lau** [comment]
Also, what happens if Mutation doesn't have any `selection`? Would it error or ignore?

**Comment by anyx** [comment]
Added `setAlias` and 'find' methods. Right now there is no any error in case with empty selection.

**Comment by anyx** [comment]
Also, current shape of mutations expects only variables, so i don`t know, where `Enum` can be used.

**Comment by A-ZC-Lau** [comment]
I'm a little confused on how mutation actually works. There doesn't seem to be anyway to actually assign values to variables?

Also if mutation doesn't work with enum, that's probably a step backward.

I just reread the graphql documentation to try and understand your approach, but it doesn't seem like this has very many benefits at this point in time. Mutations and Queries and basically the same thing, but just with "mutation" or "query" prepended.

I don't think there's any real need to separate Query and Mutation into different classes. If you want to eliminate the necessity of wrapping the QueryBuilder into another string e.g.

```
{
    query {
         ${QueryBuilder_query}
    }
}
```

Then using a parameter i.e. `type` should suffice in doing this.

**Comment by anyx** [comment]
My realization of mutations builds strings like in this example: https://graphql.org/learn/queries/#mutations
and i am using them in my project's tests
There is a bit difference between queries and mutations, I think

**Comment by A-ZC-Lau** [comment]
There's only a small difference. Queries are parallel while Mutations are serial. Read the second answer to this: https://stackoverflow.com/questions/48003767/what-is-difference-between-mutation-and-query

Also, how do you assign what goes into each variable? What happens if I have this query?
```
        let mutation = new Mutation(
            "addProduct",
            { categoryId: "new id", productData: "{ json_data: 123 }" },
            ["id", "title", {category: ["id", "title"]}, "active"]
        );
```

**Comment by anyx** [comment]
I use mutations exactly like in example from my previous comment: i send `query` with string that i build and in key `variables` i set all described variables.
So payload to graphql endpoint looks like:
```
{
  query: `mutation addProduct($categoryId: ID!, $productData: ProductInput!) {
          product: addProduct(categoryId: $categoryId, productData: $productData) {
            id,
            title
          }
        }
        `,
  variables: {
    categoryId: 1,
    productData: {
       name: 'Some Product'
    }
  }
}
```

**Comment by A-ZC-Lau** [comment]
I see, the readme wasn't very clear on that. I'm not sure what the advantage is with the new Mutation though, since we're already using javascript to create variables. Also, I still view the separation of Query and Mutation as highly unnecessary.

**Comment by anyx** [comment]
How we can build string 
```
addProduct($categoryId: ID!, $productData: ProductInput!) {
  product: addProduct(categoryId: $categoryId, productData: $productData) {
    id,
    title
  }
}
```
with `Query` from current master?

**Comment by A-ZC-Lau** [comment]
We can't. But there's no need to separate it into Query and Mutation classes. And there's no option to not use variables.

And since we won't need separate classes we can just use the default `QueryBuilder` instead.

**Comment by anyx** [comment]
@FunnyB0y can you give an example, how lib should build mutations since we don`t want to separate classes? It should be in different methods, method signatures or something?

**Comment by A-ZC-Lau** [comment]
well I'm not sure if you are trying to bundle it all into one so we don't need to pass it through a secondary string converter i.e. current build:

```
let query =
  new QueryBuidlder(
    "someQuery"
  )
let graphql_query =
`
    query
    {
    	${query}
    }
  `
```

or if you're just misunderstanding the difference between a Mutation and a Query.

**Comment by anyx** [comment]
Yes, there is definitely some misunderstanding here)
I just tried to add mutation builder which I use in my project's tests. It's not cover all cases: just mutations with variables and that's enough for me now.

Since I don't understand what should I do in this PR, you can close this i think

**Comment by A-ZC-Lau** [comment]
Sure. If you're interested in adding variables and stuff, it will be better to use some kind of options variable. Because there are features that are still not included in this like Fragments and Directives

**Pull request closed without merging**
